# Generated by Django 6.0.1 on 2026-01-21 05:59

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Brand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("BrandName", models.CharField(max_length=100, unique=True)),
            ],
            options={
                "db_table": "Brands",
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("CategoryName", models.CharField(max_length=100, unique=True)),
            ],
            options={
                "verbose_name_plural": "Categories",
                "db_table": "Categories",
                "ordering": ["CategoryName"],
            },
        ),
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "CustomerID",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("CustomerName", models.CharField(max_length=255)),
                ("City", models.CharField(max_length=255)),
                ("State", models.CharField(max_length=255)),
                ("Country", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "Customers",
                "ordering": ["CustomerName"],
            },
        ),
        migrations.CreateModel(
            name="Seller",
            fields=[
                (
                    "SellerID",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("SellerName", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "db_table": "Sellers",
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "OrderID",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("OrderDate", models.DateField()),
                (
                    "PaymentMethod",
                    models.CharField(
                        choices=[
                            ("Debit Card", "Debit Card"),
                            ("Credit Card", "Credit Card"),
                            ("Amazon Pay", "Amazon Pay"),
                            ("UPI", "UPI"),
                            ("Net Banking", "Net Banking"),
                            ("Cash on Delivery", "Cash on Delivery"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "OrderStatus",
                    models.CharField(
                        choices=[
                            ("Delivered", "Delivered"),
                            ("Pending", "Pending"),
                            ("Shipped", "Shipped"),
                            ("Cancelled", "Cancelled"),
                            ("Returned", "Returned"),
                        ],
                        max_length=20,
                    ),
                ),
                ("ShippingCost", models.DecimalField(decimal_places=2, max_digits=10)),
                ("TotalAmount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "customer",
                    models.ForeignKey(
                        db_column="CustomerID",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="store.customer",
                    ),
                ),
            ],
            options={
                "db_table": "Orders",
                "ordering": ["-OrderDate"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "ProductID",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("ProductName", models.CharField(max_length=255)),
                (
                    "Brand",
                    models.ForeignKey(
                        db_column="BrandID",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="store.brand",
                    ),
                ),
                (
                    "Category",
                    models.ForeignKey(
                        db_column="CategoryID",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="store.category",
                    ),
                ),
            ],
            options={
                "db_table": "Products",
                "ordering": ["ProductName"],
            },
        ),
        migrations.CreateModel(
            name="ProductSeller",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("IsActive", models.BooleanField(default=True)),
                (
                    "product",
                    models.ForeignKey(
                        db_column="ProductID",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="store.product",
                    ),
                ),
                (
                    "seller",
                    models.ForeignKey(
                        db_column="SellerID",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="store.seller",
                    ),
                ),
            ],
            options={
                "db_table": "ProductSellers",
                "unique_together": {("product", "seller")},
            },
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                ("OrderItemID", models.BigAutoField(primary_key=True, serialize=False)),
                ("Quantity", models.IntegerField()),
                ("UnitPrice", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "Discount",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1),
                        ],
                    ),
                ),
                ("Tax", models.DecimalField(decimal_places=2, max_digits=10)),
                ("LineTotal", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "order",
                    models.ForeignKey(
                        db_column="OrderID",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="store.order",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        db_column="ProductID",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="store.product",
                    ),
                ),
                (
                    "seller",
                    models.ForeignKey(
                        db_column="SellerID",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="store.seller",
                    ),
                ),
            ],
            options={
                "db_table": "OrderItems",
                "unique_together": {("order", "product", "seller")},
            },
        ),
    ]
